version: "3.8"

services:
  ai-service:
    build:
      context: ../services/ai-service
      dockerfile: Dockerfile
    container_name: ai-service
    ports:
      - "8000:8000"
    networks:
      - rabbitmq-net

  api-gateway:
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - chat-service
    networks:
      - rabbitmq-net

  rabbitmq:
    build:
      context: ../services/mq-service
      dockerfile: Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
      - "15674:15674"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - rabbitmq-net

  chat-service:
    build:
      context: ../services/chat-service
      dockerfile: Dockerfile
    container_name: chat-service

    depends_on:
      - rabbitmq
    networks:
      - rabbitmq-net

volumes:
  rabbitmq-data:

networks:
  rabbitmq-net:
